### ISSUE TITLE
undefined method `draw_relations'

### ISSUE THREAD

**Issue by poxtihc** [mosugi/redmine_editable_gantt#1]
Hi, in Redmine 2.3.0 the gantt link doesn't work

Rendered plugins/redmine_editable_gantt/app/views/gantts/show.html.erb within layouts/base (27.1ms)
Completed 500 Internal Server Error in 150ms

ActionView::Template::Error (undefined method `draw_relations' for #<IssueQuery:0x000000099226e8>):
    30:           <fieldset>
    31:             <legend><%= l(:label_related_issues) %></legend>
    32:             <label for="draw_relations">
    33:               <%= check_box 'query', 'draw_relations', :id => 'draw_relations' %>
    34:               <% rels = [IssueRelation::TYPE_BLOCKS, IssueRelation::TYPE_PRECEDES] %>
    35:               <% rels.each do |rel| %>
    36:                 <% color = Redmine::Helpers::Gantt::DRAW_TYPES[rel][:color] %>
  app/controllers/gantts_controller.rb:43:in `block (2 levels) in show'
  app/controllers/gantts_controller.rb:42:in `show'

Regards,

Antonio

**Comment by mosugi** [comment]
Sorry, This plugin under development.
This plugin is overwritten the view(show.html) for gantt.
show.html based on 2.6.1,maybe plugin doesn't works under 2.5 ...
